---
- hosts: vagrantboxes
  remote_user: vagrant
  tasks:
    - name: ensure that the deployments folder is removed
      file: path=/home/vagrant/deployments state=absent


    - name: create deployments folder
      file: path=/home/vagrant/deployments state=directory

    #- name: update the repository
    #  sudo: true
    #  apt: update_cache=yes

    - name: install cowsay
      sudo: yes
      apt: name=cowsay state=latest

- hosts: vagrantboxes
  remote_user: vagrant
  tasks:
    - name: install unzip
      sudo: true
      apt: name=unzip state=latest

- hosts: vagrantboxes
  remote_user: vagrant
  sudo: false
  vars:
    source_file: files/requirements.txt
    destination_folder: deployments/files
    name: ben
    address: P. O. Box 4192, Accra
    phone: +233245001853

  tasks:

    - name: create files subfolder
      file: path=/home/vagrant/{{destination_folder}} state=directory

    - name: copy the spec file to deployments folder
      template: src={{ source_file }} dest=/home/vagrant/{{destination_folder}}/ owner=vagrant