---
- hosts: vagrantboxes
  remote_user: vagrant
  tasks:
    - name: ensure that the deployments folder is removed
      file: path=/home/vagrant/deployments state=absent
    - name: create deployments folder
      file: path=/home/vagrant/deployments state=directory

