---
- hosts: vagrantboxes
  remote_user: vagrant
  tasks:
    - name: ensure that the deployments folder is removed
      file: path=/home/vagrant/deployments state=absent


    - name: create deployments folder
      file: path=/home/vagrant/deployments state=directory

    - name: update the repository
      sudo: true
      apt: update_cache=yes

    - name: install cowsay
      sudo: yes
      apt: name=cowsay state=latest

- hosts: vagrantboxes
  remote_user: vagrant
  tasks:
    - name: install unzip
      sudo: true
      apt: name=unzip state=latest

- hosts: vagrantboxes
  remote_user: vagrant
  sudo: true
  vars:
    source_folder: files/requirements.txt
    destination_folder: deployments/files

  tasks:

    - name: create files subfolder
      file: path=/home/vagrant/{{destination_folder}} state=directory